### PR TITLE
 Update `.uls-lcd-region-title` to conform to WCAG level AA

### PR DESCRIPTION
**Pull request by Volker-E**
Updating `.uls-lcd-region-title` to be on the safe side with color contrast, 
conforming to WCAG level AA no matter what `background-color` grey or `font-size`.

### CODE REVIEW

**Comment by Nikerabbit** [comment]
@pauginer Could you check this. In the screenshot below, "Ehdotetut kielet" with new color and "Maailmankielet" with old color, for illustration.

image

**Comment by pauginer** [comment]
I'm ok in increasing the contrast for accessibility reasons, but I guess we should use #54595d instead in order to also align the colors with [our color palette](https://wikimedia.github.io/WikimediaUI-Style-Guide/visual-style_colors.html)

**Comment by Volker-E** [comment]
@pauginer @Nikerabbit My thinking behind this change was, that this is a library, that also happens to be used (foremost?) in Wikimedia Foundation environments. Therefore I would go with a higher contrast, neutral grey here and overwrite specifically for Vector/MinervaNeue theme there with a grey from our palette. Thoughts?

**Comment by Nikerabbit** [comment]
That sounds okay to me. There isn't clear practice whether these libs follow our color palette. It would probably be easier if they did, assuming that non-ULS users are either happy with our defaults or will overwrite those anyway.

**Comment by Volker-E** [comment]
@Nikerabbit Sure, overwriting when not it's not appealing is always a possibility. But there is a plan to make MediaWiki not look like Wikimedia Foundation out-of-box, we have been discussing quite a while ago in Front-end developer group meeting and it dates back even longer. If another organization would use the defaults, it doesn't resemble too close Wikipedia.
So going with WCAG level AA defaults that are more neutral currently seems to be the best possible path for a library like this.

**Pull request merged**
